#!/usr/bin/env bash
set -euo pipefail

# fix_doubled_fastq.sh
# Generated by Claude
# Removes the second half of FASTQ files that have been erroneously duplicated.
# Usage: bash fix_doubled_fastq.sh sample1_R1.fastq.gz sample1_R2.fastq.gz ...
#    or: bash fix_doubled_fastq.sh *.fastq.gz

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <sample1.fastq.gz> [sample2.fastq.gz ...]"
    exit 1
fi

for INPUT in "$@"; do

    # Validate input file
    if [[ ! -f "$INPUT" ]]; then
        echo "[WARN] File not found, skipping: $INPUT"
        continue
    fi

    # Derive output filename: sample.fastq.gz -> sample.fixed.fastq.gz
    OUTPUT="${INPUT%.fastq.gz}.fixed.fastq.gz"

    echo "[INFO] Processing: $INPUT"

    # Count total reads and verify duplication
    TOTAL_READS=$(zcat "$INPUT" | awk 'NR%4==1' | wc -l)

    if (( TOTAL_READS % 2 != 0 )); then
        echo "[WARN] $INPUT has an odd number of reads ($TOTAL_READS) — skipping, manual inspection needed."
        continue
    fi

    UNIQUE_READS=$(zcat "$INPUT" | awk 'NR%4==1' | sort -u | wc -l)
    EXPECTED_HALF=$(( TOTAL_READS / 2 ))

    if (( UNIQUE_READS != EXPECTED_HALF )); then
        echo "[WARN] $INPUT does not look like a simple duplication (total=$TOTAL_READS, unique=$UNIQUE_READS) — skipping."
        continue
    fi

    echo "[INFO]   Total reads: $TOTAL_READS | Unique: $UNIQUE_READS — confirmed doubled file."

    # Extract first half (unique_reads * 4 lines)
    LINES=$(( UNIQUE_READS * 4 ))
    zcat "$INPUT" | head -n "$LINES" | gzip > "$OUTPUT"

    # Verify output read count
    OUT_READS=$(zcat "$OUTPUT" | awk 'NR%4==1' | wc -l)
    if (( OUT_READS == UNIQUE_READS )); then
        echo "[INFO]   Written: $OUTPUT ($OUT_READS reads) ✓"
    else
        echo "[ERROR]  Output read count mismatch for $OUTPUT (expected $UNIQUE_READS, got $OUT_READS)"
        exit 1
    fi

done

echo "[DONE] All files processed."
