#!/bin/sh
#SBATCH --job-name Mariana-CBR
#SBATCH --partition=hotel
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16GB
#SBATCH --time=04:00:00 
#SBATCH --qos=hotel
#SBATCH --account=htl124
#SBATCH --export=ALL
#SBATCH --output /tscc/lustre/ddn/scratch/dwc001/logs/slurm-%A_%a.out-%N
#SBATCH --output /tscc/lustre/ddn/scratch/dwc001/logs/slurm-%A_%a.err-%N
#SBATCH --mail-type END
#SBATCH --mail-user dwc001@ucsd.edu
#SBATCH --array=1-3

. /tscc/projects/ps-winzelerlab/SEQUENCING/Winzeler/Mariana/CBR-001-854-181-6_Dd2B2_Batch2/config.cfg

module load shared
module load samtools

readarray samples < $samples_file
samples=(null ${samples[@]}) # zero to one start index
sample=${samples[$SLURM_ARRAY_TASK_ID]}
echo $sample

readarray fastq_samples < $fastq_samples_file
fastq_samples=(null ${fastq_samples[@]}) # zero to one start index
fastq_sample=${fastq_samples[$SLURM_ARRAY_TASK_ID]}
echo $fastq_sample

# ================================================================================

echo "Running minimap on ${sample}"

minimap2 -t 8 -ax map-ont $ref_fasta ${fastq_dir}/${fastq_sample}.fastq.gz > $main_dir/${sample}.sam

echo "Converting sam to bam"

samtools view -@ 8 -bS -o $main_dir/${sample}.bam $main_dir/${sample}.sam

echo "Sorting bam"

samtools sort -@ 8 -m 1G -O bam -o $main_dir/${sample}_sorted.bam $main_dir/${sample}.bam

echo "Create index"

samtools index $main_dir/${sample}_sorted.bam

source "/tscc/nfs/home/dwc001/miniconda3/etc/profile.d/conda.sh"
conda activate medaka_env

echo "Run Longshot"

longshot --bam $main_dir/${sample}_sorted.bam --ref $ref_fasta --out $main_dir/${sample}.longshot.vcf --sample_id $sample --no_haps

echo "Run SnpEff"

java -jar $snpeff_dir/snpEff.jar -formatEFF -o vcf -ud 1000 -c $snpeff_dir/snpEff.config $snpeff_species_id $main_dir/${sample}.longshot.vcf > $main_dir/${sample}.longshot.vcf.ann.txt

echo "Done!"


