#!/bin/sh
#SBATCH --job-name callvar
#SBATCH --partition=hotel
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=16G
#SBATCH --ntasks-per-node=1
#SBATCH --time=40:00:00 
#SBATCH --qos=hotel
#SBATCH --account=htl124
#SBATCH --export=ALL
#SBATCH --exclude tscc-11-2
#SBATCH --output /tscc/lustre/ddn/scratch/dwc001/logs/slurm-%A_%a.out-%N
#SBATCH --output /tscc/lustre/ddn/scratch/dwc001/logs/slurm-%A_%a.err-%N
#SBATCH --mail-type END
#SBATCH --mail-user dwc001@ucsd.edu

. /tscc/projects/ps-winzelerlab/SEQUENCING/Winzeler/Mariana/CBR-001-854-181-6_Dd2B2_Batch2/config.cfg

module load shared
module load samtools

echo "Run mpileup variant calling"

bcftools mpileup -d 1000000 -a FORMAT/AD,FORMAT/DP -Q 5 -A -B -f $ref_fasta -Ou -b $bam_list | bcftools call -mv -Ov -o $main_dir/${group_name}.combined.pileup.vcf

echo "Run SnpEff"

java -jar $snpeff_dir/snpEff.jar -formatEFF -o vcf -ud 1000 -c $snpeff_dir/snpEff.config $snpeff_species_id $main_dir/${group_name}.combined.pileup.vcf > $main_dir/${group_name}.combined.pileup.vcf.ann.txt

echo "Done!"

'''
source "/tscc/nfs/home/dwc001/miniconda3/etc/profile.d/conda.sh"
conda activate medaka_env

echo "Run Longshot"

longshot --bam $main_dir/${sample}_sorted.bam --ref $ref_fasta --out $main_dir/${sample}.longshot.vcf --sample_id $sample --no_haps
'''
